title: Grid
description: Documentation for my Grid
baseurl: "/grid" # Replace with your repository name
url: "https://gridlang.github.io" # Replace with your GitHub username
theme: jekyll-theme-gitbook
markdown: kramdown
kramdown:
  input: GFM
