name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build site
        run: mdbook build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/book

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
